version: '3'
services:
  app:
    container_name: pet-finder-api
    build: .
    volumes:
      - ./:/var/www/html
      - logs:/var/www/html/storage/logs
      - /home/cesar/Dev/configs/Pet-Finder/api-config/.env:/var/www/html/.env
    ports:
      - "9000:80"
    restart: always

volumes:
  logs:
